use yokogushi_core::{Skill, SkillCategory::*};

pub static SKILLS: &[Skill] = &[
    Skill {
        id: "rust",
        name: "Rust",
        category: Language,
        aliases: &[],
    },
    Skill {
        id: "typescript",
        name: "TypeScript",
        category: Language,
        aliases: &["ts"],
    },
    Skill {
        id: "javascript",
        name: "JavaScript",
        category: Language,
        aliases: &["js"],
    },
    Skill {
        id: "python",
        name: "Python",
        category: Language,
        aliases: &["py"],
    },
    Skill {
        id: "go",
        name: "Go",
        category: Language,
        aliases: &["golang"],
    },
    Skill {
        id: "java",
        name: "Java",
        category: Language,
        aliases: &[],
    },
    Skill {
        id: "kotlin",
        name: "Kotlin",
        category: Language,
        aliases: &[],
    },
    Skill {
        id: "swift",
        name: "Swift",
        category: Language,
        aliases: &[],
    },
    Skill {
        id: "ruby",
        name: "Ruby",
        category: Language,
        aliases: &[],
    },
    Skill {
        id: "php",
        name: "PHP",
        category: Language,
        aliases: &[],
    },
    Skill {
        id: "c",
        name: "C",
        category: Language,
        aliases: &[],
    },
    Skill {
        id: "cpp",
        name: "C++",
        category: Language,
        aliases: &["cplusplus"],
    },
    Skill {
        id: "csharp",
        name: "C#",
        category: Language,
        aliases: &["csharp", "dotnet"],
    },
    Skill {
        id: "scala",
        name: "Scala",
        category: Language,
        aliases: &[],
    },
    Skill {
        id: "elixir",
        name: "Elixir",
        category: Language,
        aliases: &[],
    },
    Skill {
        id: "haskell",
        name: "Haskell",
        category: Language,
        aliases: &[],
    },
    Skill {
        id: "dart",
        name: "Dart",
        category: Language,
        aliases: &[],
    },
    Skill {
        id: "lua",
        name: "Lua",
        category: Language,
        aliases: &[],
    },
    Skill {
        id: "react",
        name: "React",
        category: Framework,
        aliases: &["reactjs"],
    },
    Skill {
        id: "nextjs",
        name: "Next.js",
        category: Framework,
        aliases: &["next"],
    },
    Skill {
        id: "vue",
        name: "Vue.js",
        category: Framework,
        aliases: &["vue", "vuejs"],
    },
    Skill {
        id: "nuxt",
        name: "Nuxt",
        category: Framework,
        aliases: &["nuxtjs"],
    },
    Skill {
        id: "svelte",
        name: "Svelte",
        category: Framework,
        aliases: &["sveltekit"],
    },
    Skill {
        id: "angular",
        name: "Angular",
        category: Framework,
        aliases: &[],
    },
    Skill {
        id: "express",
        name: "Express",
        category: Framework,
        aliases: &["expressjs"],
    },
    Skill {
        id: "nestjs",
        name: "NestJS",
        category: Framework,
        aliases: &["nest"],
    },
    Skill {
        id: "django",
        name: "Django",
        category: Framework,
        aliases: &[],
    },
    Skill {
        id: "fastapi",
        name: "FastAPI",
        category: Framework,
        aliases: &[],
    },
    Skill {
        id: "flask",
        name: "Flask",
        category: Framework,
        aliases: &[],
    },
    Skill {
        id: "rails",
        name: "Ruby on Rails",
        category: Framework,
        aliases: &["rails", "ror"],
    },
    Skill {
        id: "spring",
        name: "Spring Boot",
        category: Framework,
        aliases: &["spring"],
    },
    Skill {
        id: "laravel",
        name: "Laravel",
        category: Framework,
        aliases: &[],
    },
    Skill {
        id: "axum",
        name: "axum",
        category: Framework,
        aliases: &[],
    },
    Skill {
        id: "actix",
        name: "actix-web",
        category: Framework,
        aliases: &["actix"],
    },
    Skill {
        id: "gin",
        name: "Gin",
        category: Framework,
        aliases: &[],
    },
    Skill {
        id: "postgres",
        name: "PostgreSQL",
        category: Database,
        aliases: &["postgres", "psql"],
    },
    Skill {
        id: "mysql",
        name: "MySQL",
        category: Database,
        aliases: &[],
    },
    Skill {
        id: "sqlite",
        name: "SQLite",
        category: Database,
        aliases: &[],
    },
    Skill {
        id: "mongodb",
        name: "MongoDB",
        category: Database,
        aliases: &["mongo"],
    },
    Skill {
        id: "redis",
        name: "Redis",
        category: Database,
        aliases: &[],
    },
    Skill {
        id: "dynamodb",
        name: "DynamoDB",
        category: Database,
        aliases: &["dynamo"],
    },
    Skill {
        id: "elasticsearch",
        name: "Elasticsearch",
        category: Database,
        aliases: &["es", "elastic"],
    },
    Skill {
        id: "docker",
        name: "Docker",
        category: Infrastructure,
        aliases: &[],
    },
    Skill {
        id: "k8s",
        name: "Kubernetes",
        category: Infrastructure,
        aliases: &["k8s"],
    },
    Skill {
        id: "aws",
        name: "AWS",
        category: Infrastructure,
        aliases: &["amazon web services"],
    },
    Skill {
        id: "gcp",
        name: "Google Cloud",
        category: Infrastructure,
        aliases: &["gcp"],
    },
    Skill {
        id: "azure",
        name: "Azure",
        category: Infrastructure,
        aliases: &[],
    },
    Skill {
        id: "terraform",
        name: "Terraform",
        category: Infrastructure,
        aliases: &[],
    },
    Skill {
        id: "github_actions",
        name: "GitHub Actions",
        category: Infrastructure,
        aliases: &["gha"],
    },
    Skill {
        id: "git",
        name: "Git",
        category: Tool,
        aliases: &[],
    },
];
